---
title: "binary logistic test"
output: html_document
date: "2023-03-10"
---
```{r}
library(dplyr)
library(stats)
```


```{r}
create_cell_name <- function(pheno_name){
  return(c(paste0(pheno_name,'-Yes'), paste0(pheno_name,'-No')))
}

simulate_binary_data <- function(var_info){
  # Generate cell counts
  cell_cnts <- c(var_info[1,'k11'], var_info[1,'k10'], var_info[1,'k01'], var_info[1,'k00'], var_info[1,'n11']-var_info[1,'k11'], var_info[1,'n10']-var_info[1,'k10'], var_info[1,'n01']-var_info[1,'k01'], var_info[1,'n00']-var_info[1,'k00'])
  
  # Input the observed counts
  observed_counts <- array(cell_cnts, dim = c(2, 2, 2), dimnames = list(create_cell_name(pheno1), create_cell_name(pheno2), c("Var-Yes", "Var-No")))
  # print(observed_counts)
  
  # Synthesize data
  bin_data = c()
  for(i in 1:2){
    for(j in 1:2){
      for(k in 1:2){
        temp <- rep(c(i==1,j==1,k==1), observed_counts[i,j,k])
        bin_data <- c(bin_data, temp)
      }
    }
  }
  bin_data <- data.frame(matrix(bin_data, ncol=3, byrow=TRUE))
  colnames(bin_data) <- c('pheno1', 'pheno2', 'Var')
  return(bin_data)
}

null_ll_function <- function(c, AC, alpha0, alpha1){
  ll <- AC*alpha_0[1] + AC_1*alpha_0[2] + AC_2*c*alpha_0[2] - n_00*log(exp(alpha_0[1]+1)+1) - n_10*log(exp(alpha_0[1]+alpha_0[2])+1)- n_01*log(exp(alpha_0[1]+c*alpha_0[2])+1) - n_11*log(exp(alpha_0[1]+(c+1)*alpha_0[2])+1)
  return(ll)
}

build_null_loglik <- function(bin_data, c){
  bin_data$pheno0 <- bin_data[,1] + c* bin_data[,2]
  log_0 <- glm(Var ~ pheno0,family=binomial(link='logit'),data=bin_data)
  p <- summary(log_0)$coefficients[2,4]
  alpha_0 <- log_0$coefficients
  # solve the MLE of c
  u = (AC_2-n_01-n_11)*exp(alpha_0[2])
  v = (AC_2-n_11)*exp(alpha_0[2])+(AC_2-n_01)
  w = AC_2
  x1 = (-v+sqrt(v^2-4*u*w))/(2*u)
  x2 = (-v-sqrt(v^2-4*u*w))/(2*u)
  c_mle = (log(x2)-alpha_0[1])/alpha_0[2]
  # log likelihood under the alternative
  ll_0 <- AC*alpha_0[1] + AC_1*alpha_0[2] + AC_2*c_mle*alpha_0[2] - n_00*log(exp(alpha_0[1]+1)+1) - n_10*log(exp(alpha_0[1]+alpha_0[2])+1)- n_01*log(exp(alpha_0[1]+c_mle*alpha_0[2])+1) - n_11*log(exp(alpha_0[1]+(c_mle+1)*alpha_0[2])+1)
  return(list(c=c_mle, ll=ll_0, p=p))
}

build_alt_loglik <- function(bin_data){
  log_1 <- glm(Var ~ pheno1 + pheno2, family=binomial(link='logit'),data=bin_data)
  alpha_1 <- log_1$coefficients
  
  # log likelihood under the alternative
  ll_1 <- AC*alpha[1] + AC_1*alpha[2] + AC_2*alpha[3] - n_00*log(exp(alpha[1]+1)+1) - n_10*log(exp(alpha[1]+alpha[2])+1)- n_01*log(exp(alpha[1]+alpha[3])+1) - n_11*log(exp(alpha[1]+alpha[2]+alpha[3])+1)
  return(ll_1)
}

build_loglik_ratio <- function(k_11, k_10, k_01, k_00, n_11, n_10, n_01, n_00, pheno1, pheno2){
  AC <- k_11 + k_10 + k_01 + k_00
  AC_1 <- k_11 + k_10
  AC_2 <- k_11 + k_01
  bin_data <- simulate_binary_data(k_11, k_10, k_01, k_00, n_11, n_10, n_01, n_00, pheno1, pheno2)
  ll_1 <- build_alt_loglik(bin_data)
  print(paste0('The log-likelihood under the alternative is', ll_1))
  print(paste0('Updating c to get the log-likelihood under the null....'))
  c = 0
  ll_max = 0
  result = build_null_loglik(bin_data, c)
  c = result[[1]]
  ll_0 = result[[2]]
  i = 0
  while(abs(ll_0 -ll_max) > 1e-100){
    if(ll_0>ll_max){
      ll_max = ll_0
    }
    i = i+1
    print(paste0('-------------ROUND ', i, '------------------'))
    print(paste0('current c:', c))
    result = build_null_loglik(bin_data, c)
    c_mle = result[[1]]
    ll_0 = result[[2]]
    print(paste0('new c:', c_mle))
    c = c_mle
    print(paste0('current ll_0:', ll_0))
    print(paste0('current ll_max:', ll_max))
  }
  ratio = -2*(ll_1-ll_0)
  return(ratio)
}
```

```{r}
k_11 <- 1
k_10 <- 1
k_01 <- 0
k_00 <- 33
n_11 <- 178
n_10 <- 23975
n_01 <- 286
n_00 <- 370402
pheno1 <- 'E11'
pheno2 <- 'I11'
```

```{r}
AC <- k_11 + k_10 + k_01 + k_00
AC_1 <- k_11 + k_10
AC_2 <- k_11 + k_01
cell_cnts <- c(k_11, k_10, k_01, k_00, n_11-k_11, n_10-k_10, n_01-k_01, n_00-k_00)
```

```{r}
# Input the observed counts
observed_counts <- array(cell_cnts, dim = c(2, 2, 2), dimnames = list(create_cell_name(pheno1), create_cell_name(pheno2), c("Var-Yes", "Var-No")))

# Calculate the marginal totals for each variable
row_totals <- apply(observed_counts, c(2, 3), sum)
col_totals <- apply(observed_counts, c(1, 3), sum)
layer_totals <- apply(observed_counts, c(1, 2), sum)
table_total <- sum(observed_counts)

# Synthesize data
bin_data = c()
for(i in 1:2){
  for(j in 1:2){
    for(k in 1:2){
      temp <- rep(c(i==1,j==1,k==1), observed_counts[i,j,k])
      bin_data <- c(bin_data, temp)
    }
  }
}
bin_data <- data.frame(matrix(bin_data, ncol=3, byrow=TRUE))
colnames(bin_data) <- c(pheno1, pheno2, 'Var')

```

```{r}
# Use logistic regression to solve parameters
log_1 <- glm(Var ~ I11 + E11,family=binomial(link='logit'),data=bin_data)
summary(log_1)
```

```{r}
alpha <- log_1$coefficients
```

```{r}
# log likelihood under the alternative
ll_1 <- AC*alpha[1] + AC_1*alpha[2] + AC_2*alpha[3] - n_00*log(exp(alpha[1]+1)+1) - n_10*log(exp(alpha[1]+alpha[2])+1)- n_01*log(exp(alpha[1]+alpha[3])+1) - n_01*log(exp(alpha[1]+alpha[2]+alpha[3])+1)
```



```{r}
k_11 <- 1
k_10 <- 1
k_01 <- 0
k_00 <- 33
n_11 <- 178
n_10 <- 23975
n_01 <- 286
n_00 <- 370402
n_cases1 <- n_11 + n_10
n_cases2 <- n_11 + n_01
n_controls1 <- n_01 + n_00
n_controls2 <- n_10 + n_00
pheno1 <- 'E11'
pheno2 <- 'I11'
AC <- k_11 + k_10 + k_01 + k_00
AC_1 <- k_11 + k_10
AC_2 <- k_11 + k_01
var_cnt_data <- data.frame(matrix(ncol = 12, nrow = 0))
var1 <- c('var1', pheno1, pheno2, n_cases1, n_cases2, n_controls1, n_controls2, AC_1, AC_2, AC, k_11, n_11)
var_cnt_data <- rbind(var_cnt_data, var1)
```


```{r}
n_11 <- 178
n_10 <- 23975
n_01 <- 286
n_00 <- 370402
n_cases1 <- n_11 + n_10
n_cases2 <- n_11 + n_01
n_controls1 <- n_01 + n_00
n_controls2 <- n_10 + n_00
pheno1 <- 'E11'
pheno2 <- 'I11'
# var_cnt_data <- data.frame(matrix(ncol = 12, nrow = 0))

for(i in 1:10){
  k_11 <- floor(runif(1, 0, 5))
  k_10 <- floor(runif(1, 0, 30))
  k_01 <- floor(runif(1, 0, 30))
  k_00 <- floor(runif(1, 0, 100))
  AC <- k_11 + k_10 + k_01 + k_00
  AC_1 <- k_11 + k_10
  AC_2 <- k_11 + k_01
  var_temp <- c(paste0('var', i), pheno1, pheno2, n_cases1, n_cases2, n_controls1, n_controls2, AC_1, AC_2, AC, k_11, n_11)
  var_cnt_data <- rbind(var_cnt_data, var_temp)
}
colnames(var_cnt_data) <- c('variant', 'pheno1', 'pheno2', 'n_cases1', 'n_cases2', 'n_controls1', 'n_controls2', 'AC_case1', 'AC_case2', 'AC_total', 'k11', 'n11')
var_cnt_data[,4:12] <- sapply(var_cnt_data[,4:12], as.numeric)
```

```{r}
var_cnt_data <- var_cnt_data %>%
  mutate(k10 = AC_case1 - k11,
         k01 = AC_case2 - k11,
         n10 = n_cases1 - n11,
         n01 = n_cases2 - n11) %>%
  mutate(k00 = AC_total - k11 - k01 - k10,
         n00 = n_controls1 - n01,
         )
```

```{r}
ll_1 <- c()
alpha_0 <- data.frame(matrix(matrix(ncol = 12, nrow = 0)))
for(i in 1:nrow(var_cnt_data)){
  bin_data <- simulate_binary_data(var_cnt_data[i,])
  
  ## log likelihood under alternative hypothesis
  log_1 <- glm(Var ~ pheno1 + pheno2,family=binomial(link='logit'),data=bin_data)
  alpha <- log_1$coefficients
  ll_1_temp <- AC*alpha[1] + AC_1*alpha[2] + AC_2*alpha[3] - n_00*log(exp(alpha[1]+1)+1) - n_10*log(exp(alpha[1]+alpha[2])+1)- n_01*log(exp(alpha[1]+alpha[3])+1) - n_01*log(exp(alpha[1]+alpha[2]+alpha[3])+1)
  ll_1 <- c(ll_1, ll_1_temp)
}
LL_1 <- sum(ll_1)
```

```{r}
c <- 1000
var_cnt_data['alpha0_log0'] <- NA
var_cnt_data['alpha1_log0'] <- NA
for(i in 1:nrow(var_cnt_data)){
  print(i)
  bin_data <- simulate_binary_data(var_cnt_data[i,])
  bin_data$pheno0 <- bin_data[,'pheno1'] + c* bin_data[,'pheno2']
  log_0 <- glm(Var ~ pheno0,family=binomial(link='logit'),data=bin_data)
  # p <- summary(log_0)$coefficients[2,4]
  var_cnt_data[i, 'alpha0_log0'] <- log_0$coefficients[1]
  var_cnt_data[i, 'alpha1_log0'] <- log_0$coefficients[2]
}
compute_ll_0 <- function(c, var_cnt_data){
  var_cnt_data <- var_cnt_data %>%
      mutate(ll_0 = AC_total*alpha0_log0 + AC_case1*alpha1_log0 + AC_case2*c*alpha1_log0 - n00*log(exp(alpha0_log0)+1) - n10*log(exp(alpha0_log0+alpha1_log0)+1)- n01*log(exp(alpha0_log0+c*alpha1_log0)+1) - n11*log(exp(alpha0_log0+(c+1)*alpha1_log0)+1))
  LL_0 <- sum(var_cnt_data$ll_0)
  return(LL_0)
}
compute_ll_0(c, var_cnt_data)
```

```{r}
ll_0_lst <- c()
c_lst <- seq(-10, 10, by = 0.01)
ll_0_lst <- sapply(c_lst, compute_ll_0, var_cnt_data=var_cnt_data)
plot(c_lst, ll_0_lst)
c_mle = c_lst[which(ll_0_lst==max(ll_0_lst))]
c_mle

```


```{r}
c <- 100
j <- 0
c_mle <- 0
ll_0_max <- -1e100
previous_ll_0_max <- 1
var_cnt_data['alpha0_log0'] <- NA
var_cnt_data['alpha1_log0'] <- NA
c_lst <- seq(-10, 100, by = 0.1)
ll_0_lst <- c()
for(c in c_lst){
  j = j+1
  # c = c_mle
  print(paste0('-------------ROUND ', j, '------------------'))
  print(paste0('current c:', c))
  for(i in 1:nrow(var_cnt_data)){
    # print(paste0('Variant', i))
    bin_data <- simulate_binary_data(var_cnt_data[i,])
    bin_data$pheno0 <- bin_data[,'pheno1'] + c* bin_data[,'pheno2']
    log_0 <- glm(Var ~ pheno0,family=binomial(link='logit'),data=bin_data)
    # p <- summary(log_0)$coefficients[2,4]
    var_cnt_data[i, 'alpha0_log0'] <- log_0$coefficients[1]
    var_cnt_data[i, 'alpha1_log0'] <- log_0$coefficients[2]
  }
  LL_0 <- compute_ll_0(c, var_cnt_data)
  ll_0_lst <- c(ll_0_lst, LL_0)
  # print(paste0('current LL_0:', LL_0))
  # ll_0_lst <- c()
  # ll_0_lst <- sapply(c_lst, compute_ll_0, var_cnt_data=var_cnt_data)
  # plot(c_lst, ll_0_lst)
  # c_mle = c_lst[which(ll_0_lst==max(ll_0_lst))]
  # if(LL_0 > ll_0_max){
  #   c_mle = c_lst[which(ll_0_lst==max(ll_0_lst))]
  #   previous_ll_0_max = ll_0_max
  #   ll_0_max = LL_0
  # }
  # print(paste0('c_mle:', c_mle))
  # print(paste0('potential ll_0_max:', max(ll_0_lst)))
}
plot(c_lst, ll_0_lst)
```

```{r}
c <- 0
c_mle <- 100
j <- 0
previous_c <- 10
ll_0_max <- -1e100
previous_ll_0_max <- 1
var_cnt_data['alpha0_log0'] <- NA
var_cnt_data['alpha1_log0'] <- NA
c_lst <- seq(-10, 500, by = 0.1)
while(c != c_mle){
  j = j+1
  # c = c_mle
  print(paste0('-------------ROUND ', j, '------------------'))
  print(paste0('current c:', c))
  for(i in 1:nrow(var_cnt_data)){
    bin_data <- simulate_binary_data(var_cnt_data[i,])
    bin_data$pheno0 <- bin_data[,'pheno1'] + c* bin_data[,'pheno2']
    log_0 <- glm(Var ~ pheno0,family=binomial(link='logit'),data=bin_data)
    # p <- summary(log_0)$coefficients[2,4]
    var_cnt_data[i, 'alpha0_log0'] <- log_0$coefficients[1]
    var_cnt_data[i, 'alpha1_log0'] <- log_0$coefficients[2]
  }
  LL_0 <- compute_ll_0(c, var_cnt_data)
  print(paste0('current LL_0:', LL_0))
  ll_0_lst <- c()
  ll_0_lst <- sapply(c_lst, compute_ll_0, var_cnt_data=var_cnt_data)
  plot(c_lst, ll_0_lst)
  # c_mle = c_lst[which(ll_0_lst==max(ll_0_lst))]
  previous_c = c
  if(LL_0 > ll_0_max){
    c_mle = c
    ll_0_max = LL_0
  }
  c = c_lst[which(ll_0_lst==max(ll_0_lst))]
  print(paste0('c_mle:', c_mle))
  print(paste0('ll_0_max:', ll_0_max))
}
LL_0 <- ll_0_max
```


```{r}
new_c_lst <- seq(c_mle-5, c_mle+5, 0.001)
c <- 0
j <- 0
while(abs(c-c_mle)>0){
  j = j+1
  c = c_mle
  print(paste0('-------------ROUND ', j, '------------------'))
  print(paste0('current c:', c))
  for(i in 1:nrow(var_cnt_data)){
    # print(paste0('Variant', i))
    bin_data <- simulate_binary_data(var_cnt_data[i,])
    bin_data$pheno0 <- bin_data[,'pheno1'] + c* bin_data[,'pheno2']
    log_0 <- glm(Var ~ pheno0,family=binomial(link='logit'),data=bin_data)
    # p <- summary(log_0)$coefficients[2,4]
    var_cnt_data[i, 'alpha0_log0'] <- log_0$coefficients[1]
    var_cnt_data[i, 'alpha1_log0'] <- log_0$coefficients[2]
  }
  ll_0_lst <- c()
  ll_0_lst <- sapply(new_c_lst, compute_ll_0, var_cnt_data=var_cnt_data)
  plot(new_c_lst, ll_0_lst)
  if(max(ll_0_lst) > ll_0_max){
    c_mle = new_c_lst[which(ll_0_lst==max(ll_0_lst))]
    previous_ll_0_max = ll_0_max
    ll_0_max = max(ll_0_lst) 
  }
  print(paste0('c_mle:', c_mle))
  print(paste0('current ll_0_max:', ll_0_max))
}
```


```{r}
LR = -2*(LL_1 - LL_0)
1 - pchisq(LR, 10)
```
```{r}
p <- d %>%
  filter(ll_0_lst != -Inf) %>%
  # filter(c_lst > 0.4) %>%
  ggplot + aes(x = c_lst, y = ll_0_lst) + 
  geom_point() + 
  labs(x = 'c', y = 'LL_0') + 
  # scale_x_continuous(breaks = c(1.2, 25, 50, 75, 100)) + 
  # xlim(0.4, 10)
  geom_vline(xintercept = 1.2, lty=2, color = 'red')
png(paste0(figure_path, 'bin_test_c_mle_full.png'), height = 4, width = 6, units = 'in', res = 300)
print(p)
dev.off() 
```

```{r}
ll <- lapply(var_cnt_data,function(var_cnt_data)
    optimize(compute_ll_0,c(-5,5), var_cnt_data=var_cnt_data))

ll[[which.min(sapply(ll,'[[','maximum'))]]

```

